services:
  lir_api:
    image: mariiaprylutska/lir_backend
    restart: always
    links:
      - lir_db:lir_db
    build:
      context: .
    depends_on:
      - lir_db
    ports:
      - 8080:8080
  lir_db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  lir_db: