services:
  lir.api:
    image: mariiaprylutska/lir_backend
    restart: always
    links:
      - lir.db:lir.db
    build:
      context: .
    depends_on:
      - lir.db
    ports:
      - 3000:8080
    networks:
      - app
  lir.db:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - app
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  lir.db:
networks:
  app:
    driver: bridge