name: lir-ci
on:
  push: 
    branches: [main, develop]
  pull_request: 
    branches: [main, develop]
jobs:
  build_and_push: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: login docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push
        run: |
          docker build -t mariiaprylutska/lir_backend .
          docker push mariiaprylutska/lir_backend
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            docker pull mariiaprylutska/lir_backend 
            cd lir_backend
            docker-compose up -d
